import argparse
import gzip
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "web" / "src"
INPUT_FILE = SOURCE_DIR / "index.html"
BUNDLE_FILE = ROOT / "web" / "dist" / "index.html"
OUTPUT_FILE = ROOT / "include" / "ui_index.h"

SCRIPT_PATTERN = re.compile(r'<script\s+src="([^"]+)"\s*></script>')
STYLE_PATTERN = re.compile(r'<link\s+rel="stylesheet"\s+href="([^"]+)"\s*/?>')


def read_local_asset(reference: str) -> str:
    asset = (SOURCE_DIR / reference).resolve()
    try:
        asset.relative_to(SOURCE_DIR.resolve())
    except ValueError as error:
        raise ValueError(f"Asset escapes web/src: {reference}") from error
    if not asset.is_file():
        raise FileNotFoundError(f"Missing frontend asset: {reference}")
    return asset.read_text(encoding="utf-8").rstrip()


def bundle_source() -> bytes:
    html = INPUT_FILE.read_text(encoding="utf-8")

    def inline_script(match: re.Match[str]) -> str:
        reference = match.group(1)
        return f"<script>\n{read_local_asset(reference)}\n</script>"

    def inline_style(match: re.Match[str]) -> str:
        reference = match.group(1)
        return f"<style>\n{read_local_asset(reference)}\n</style>"

    html = SCRIPT_PATTERN.sub(inline_script, html)
    html = STYLE_PATTERN.sub(inline_style, html)
    return html.encode("utf-8")


def render_header(html_content: bytes) -> str:
    gzipped_content = gzip.compress(html_content, mtime=0)
    hex_array = ", ".join(f"0x{byte:02x}" for byte in gzipped_content)
    return f"""#ifndef UI_INDEX_H
#define UI_INDEX_H

#include <stdint.h>
#include <pgmspace.h>

// Generated by web/make_ui_header.py. Do not edit by hand.
const uint8_t UI_INDEX_GZ[] PROGMEM = {{
    {hex_array}
}};
const size_t UI_INDEX_GZ_LEN = sizeof(UI_INDEX_GZ);

#endif // UI_INDEX_H
"""


def check_file(path: Path, expected: bytes) -> bool:
    return path.is_file() and path.read_bytes() == expected


def main() -> int:
    parser = argparse.ArgumentParser(description="Bundle and embed the offline PyroVue frontend")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in embedded header is stale",
    )
    args = parser.parse_args()

    html_content = bundle_source()
    header_content = render_header(html_content).encode("utf-8")

    if args.check:
        if not check_file(OUTPUT_FILE, header_content):
            print(f"Stale generated frontend file: {OUTPUT_FILE.relative_to(ROOT)}")
            return 1
        print("Embedded frontend header is current")
        return 0

    BUNDLE_FILE.parent.mkdir(parents=True, exist_ok=True)
    BUNDLE_FILE.write_bytes(html_content)
    OUTPUT_FILE.write_bytes(header_content)
    gzipped_size = len(gzip.compress(html_content, mtime=0))
    print(f"Bundled {INPUT_FILE.relative_to(ROOT)} to {BUNDLE_FILE.relative_to(ROOT)}")
    print(f"Generated {OUTPUT_FILE.relative_to(ROOT)}")
    print(f"Bundle size: {len(html_content)} bytes; gzip size: {gzipped_size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
